name: "test"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  lint: 
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: "^1.16"
    - name: "Tidy"
      run: |
        GO_MOD_OUPUT="$(go mod tidy -v 2>&1)"
        if [[ $GO_MOD_OUPUT == *"unused"* ]]; then
          echo "${GO_MOD_OUPUT}"
          exit 1
        fi
    - uses: "authzed/actions/gofumpt@main"
    - name: "Lint"
      run: |
        go install github.com/mgechev/revive@latest
        revive ./...

  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: "^1.16"
    - name: "Test"
      run: "go test ./..."
